import Providers from "@/providers/Providers";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

// Import Poppins Font
const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "TutorLink",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} font-poppins antialiased`}>
				<Providers>
					<Toaster
						richColors
						toastOptions={{
							style: {
								background: "#ffff",
								color: "#ac0ed4e5",
							},
						}}
						position="top-right"
					/>
					{children}
				</Providers>
			</body>
		</html>
	);
}
